spring:
  data:
    mongodb:
      username: matheus
      password: matheus
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
